################################################## 
# TranslationNodeNotification_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from TranslationNodeNotification_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI
from ZSI.generate.pyclass import pyclass_type

# Locator
class TranslationNodeNotificationLocator:
    TranslationNodeNotificationPortType_address = "http://150.254.173.189:8086/vlbiBroker/services/TranslationNodeNotification"
    def getTranslationNodeNotificationPortTypeAddress(self):
        return TranslationNodeNotificationLocator.TranslationNodeNotificationPortType_address
    def getTranslationNodeNotificationPortType(self, url=None, **kw):
        return TranslationNodeNotificationSOAP11BindingSOAP(url or TranslationNodeNotificationLocator.TranslationNodeNotificationPortType_address, **kw)

# Methods
class TranslationNodeNotificationSOAP11BindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: chunkIsReady
    def chunkIsReady(self, request):
        if isinstance(request, chunkIsReadyRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="urn:chunkIsReady", **kw)
        #check for soap, assume soap:fault
        if self.binding.IsSOAP(): self.binding.Receive(None, **kw)

chunkIsReadyRequest = ns1.chunkIsReady_Dec().pyclass
