.Dd $Mdocdate: June 9 2008 $
.Dt EXTRACT_CHANNELIZER 3
.Os
.Sh NAME
.Nm extract_channelizer
.Nd Detect the different channelizer involved in a e-vlbi experiment. 
.Sh SYNOPSIS
.Nm extract_channelizer
.Bk -words
.Op ctrl-file
.Op vex-file
.Op output-dir
.Sh DESCRIPTION
.Nm 
parse the ctrl-file/vex-file. The involved data stream are then open to 
detect their mark5 channel organization. 
.Nm 
then try to compile a specific channelizer tune for the data stream. 
The generated channel extractor are saved as shared library in the 
given output directory (output-dir). These tuned channel_extractor 
can then be loaded (for example in SCARIe/sfxc) replacing the default 
channel_extractor speeding the extraction speed by a factor of 2. 

.Sh SEE ALSO
.Xr sfxc 3 ,
.Rs
.%A D. Marchal
.%O work in progress material
.Re
