!@This is the start of file &CALCM
!
      INTEGER*2 MAX_FLY,MAX_USE
      PARAMETER (MAX_FLY=112,
     .           MAX_USE=30)
      INTEGER*2 IAVAIL,ICLUSE
      CHARACTER*8 AVAIL(MAX_FLY),CALUSE(MAX_USE),CALFOR(MAX_USE)
      COMMON/CALCM/IAVAIL,ICLUSE,AVAIL,CALUSE,CALFOR
