!This is the start of file &CORCOM
      CHARACTER*20 PARNAM(MAX_PER)
      INTEGER*2 ARCS,LUIN,LUOUT,LUOP,ARCNUM(MAX_ARC)
      character*15 date
      COMMON/CORCOM/ARCS,LUIN,LUOUT,LUOP,ARCNUM
      COMMON/CORCOMCH/PARNAM,date
