!@This is the start of file &GLOCM
!
      LOGICAL*2 MKNRMEQ,ELARCPM,INF2COV,ARCCALC,ARCTHER,MAKCVRN,
     .          PURGARC,ADMKCGM,KGLBOUT,KOUTPUT
      COMMON /CMSTATE/ MKNRMEQ,ELARCPM,INF2COV,ARCCALC,ARCTHER,MAKCVRN,
     .                 PURGARC,ADMKCGM,KGLBOUT,KOUTPUT
