!@This is the start of file &TREMA
!
!  EMACOM declarations
!
      REAL*8 XMAT1(ELEMENTS_LONG), XMAT2(ELEMENTS_LONG)
      REAL*8 PROD(NUM_TRANSFORM,MAX_STA_PAR),SCAL(NUM_TRANSFORM)
      REAL*8 B(NUM_TRANSFORM)
      REAL*8 MAPTRN(NUM_TRANSFORM,MAX_STA_PAR)
      INTEGER*2 STAXRF(MAX_PAR)
      REAL*8 MASPOS(3,MAX_STA),TSTPOS(3,MAX_STA),A(TRANSFORM_SIZE)
      REAL*8 POSSIG(3,MAX_STA)
!
      COMMON/EMACOM/XMAT1,XMAT2,PROD,B,MAPTRN,MASPOS,
     .              TSTPOS,A,SCAL,POSSIG,STAXRF
!
