##################################################
# NewTranslationJob_services_server.py
#      Generated by ZSI.generate.wsdl2dispatch.ServiceModuleWriter
#
##################################################

from NewTranslationJob_services import *
from ZSI.ServiceContainer import ServiceSOAPBinding

class NewTranslationJob(ServiceSOAPBinding):
    soapAction = {}
    root = {}
    _wsdl = """<?xml version=\"1.0\" ?>
<wsdl:definitions targetNamespace=\"http://broker.remote.expres.psnc.pl\" xmlns:axis2=\"http://broker.remote.expres.psnc.pl\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http/\" xmlns:mime=\"http://schemas.xmlsoap.org/wsdl/mime/\" xmlns:ns0=\"http://broker.remote.expres.psnc.pl/xsd\" xmlns:ns1=\"http://jobinfo.broker.remote.expres.psnc.pl/xsd\" xmlns:soap=\"http://schemas.xmlsoap.org/wsdl/soap/\" xmlns:soap12=\"http://schemas.xmlsoap.org/wsdl/soap12/\" xmlns:wsaw=\"http://www.w3.org/2006/05/addressing/wsdl\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl/\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\">
  <wsdl:types>
    <xs:schema attributeFormDefault=\"qualified\" elementFormDefault=\"qualified\" targetNamespace=\"http://broker.remote.expres.psnc.pl/xsd\" xmlns:xsd=\"http://broker.remote.expres.psnc.pl/xsd\">
      <xs:element name=\"startTranslationJob\">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs=\"0\" name=\"param0\" nillable=\"true\" type=\"ns1:JobInfo\"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema attributeFormDefault=\"qualified\" elementFormDefault=\"qualified\" targetNamespace=\"http://jobinfo.broker.remote.expres.psnc.pl/xsd\" xmlns:ax21=\"http://jobinfo.broker.remote.expres.psnc.pl/xsd\">
      <xs:complexType name=\"JobInfo\">
        <xs:sequence>
          <xs:element minOccurs=\"0\" name=\"brokerLocation\" nillable=\"true\" type=\"xs:string\"/>
          <xs:element minOccurs=\"0\" name=\"chunkSize\" type=\"xs:long\"/>
          <xs:element minOccurs=\"0\" name=\"endTime\" nillable=\"true\" type=\"xs:string\"/>
          <xs:element minOccurs=\"0\" name=\"experimentName\" nillable=\"true\" type=\"xs:string\"/>
          <xs:element minOccurs=\"0\" name=\"gridFtpLocation\" nillable=\"true\" type=\"xs:string\"/>
          <xs:element minOccurs=\"0\" name=\"startTime\" nillable=\"true\" type=\"xs:string\"/>
          <xs:element minOccurs=\"0\" name=\"telescopeName\" nillable=\"true\" type=\"xs:string\"/>
        </xs:sequence>
      </xs:complexType>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name=\"startTranslationJobRequest\">
    <wsdl:part element=\"ns0:startTranslationJob\" name=\"parameters\"/>
  </wsdl:message>
  <wsdl:portType name=\"NewTranslationJobPortType\">
    <wsdl:operation name=\"startTranslationJob\">
      <wsdl:input message=\"axis2:startTranslationJobRequest\" wsaw:Action=\"urn:startTranslationJob\"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name=\"NewTranslationJobSOAP11Binding\" type=\"axis2:NewTranslationJobPortType\">
    <soap:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
    <wsdl:operation name=\"startTranslationJob\">
      <soap:operation soapAction=\"urn:startTranslationJob\" style=\"document\"/>
      <wsdl:input>
        <soap:body use=\"literal\"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name=\"NewTranslationJobSOAP12Binding\" type=\"axis2:NewTranslationJobPortType\">
    <soap12:binding style=\"document\" transport=\"http://schemas.xmlsoap.org/soap/http\"/>
    <wsdl:operation name=\"startTranslationJob\">
      <soap12:operation soapAction=\"urn:startTranslationJob\" style=\"document\"/>
      <wsdl:input>
        <soap12:body use=\"literal\"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name=\"NewTranslationJobHttpBinding\" type=\"axis2:NewTranslationJobPortType\">
    <http:binding verb=\"POST\"/>
    <wsdl:operation name=\"startTranslationJob\">
      <http:operation location=\"NewTranslationJob/startTranslationJob\"/>
      <wsdl:input>
        <mime:content part=\"startTranslationJob\" type=\"text/xml\"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name=\"NewTranslationJob\">
    <wsdl:port binding=\"axis2:NewTranslationJobSOAP11Binding\" name=\"NewTranslationJobSOAP11port_http\">
      <soap:address location=\"http://localhost:8080/axis2/services/NewTranslationJob\"/>
    </wsdl:port>
    <wsdl:port binding=\"axis2:NewTranslationJobSOAP12Binding\" name=\"NewTranslationJobSOAP12port_http\">
      <soap12:address location=\"http://localhost:8080/axis2/services/NewTranslationJob\"/>
    </wsdl:port>
    <wsdl:port binding=\"axis2:NewTranslationJobHttpBinding\" name=\"NewTranslationJobHttpport\">
      <http:address location=\"http://localhost:8080/axis2/services/NewTranslationJob\"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>"""

    def __init__(self, post='/axis2/services/NewTranslationJob', **kw):
        ServiceSOAPBinding.__init__(self, post)

    def soap_startTranslationJob(self, ps):
        self.request = ps.Parse(startTranslationJobRequest.typecode)
        # NO output
        return None

    soapAction['urn:startTranslationJob'] = 'soap_startTranslationJob'
    root[(startTranslationJobRequest.typecode.nspname,startTranslationJobRequest.typecode.pname)] = 'soap_startTranslationJob'

    def soap_startTranslationJob(self, ps):
        self.request = ps.Parse(startTranslationJobRequest.typecode)
        # NO output
        return None

    soapAction[''] = 'soap_startTranslationJob'
    root[(startTranslationJobRequest.typecode.nspname,startTranslationJobRequest.typecode.pname)] = 'soap_startTranslationJob'

    def soap_startTranslationJob(self, ps):
        self.request = ps.Parse(startTranslationJobRequest.typecode)
        # NO output
        return None

    soapAction[''] = 'soap_startTranslationJob'
    root[(startTranslationJobRequest.typecode.nspname,startTranslationJobRequest.typecode.pname)] = 'soap_startTranslationJob'

