Import('env')

#env.Append(LIBS='dataaccess')
#env.ParseConfig('pkg-config --cflags --libs common')
#env.ParseConfig('pkg-config --cflags --libs testunit')

sources = Split('main_test.cc')

#test_dataaccess = env.Program('#test_common', sources)
#env.Depends(test_dataaccess, '#lib/libcommon.a')

env.SetOption('implicit_cache',1)

