Import('env')

sources = Split('common.cc demangler.cc mutex.cc raiimutex.cc condition.cc thread.cc exception.cc exception_indexoutofbound.cc backtrace.cc')


sfxcinclude = "/home/damien/code/sfxc_sc07/sfxc_nico/include"
env.Append( CCFLAGS=['-Isrc/', '-I'+sfxcinclude] )

# COMPILATION OF THE LIBRARY
common_static = env.StaticLibrary('#lib/common', sources)
common_shared = env.SharedLibrary('#lib/common', sources)

# What have to be installed... the .h and the source
env.installer.AddLibrary(common_static)
env.installer.AddLibrary(common_shared)
env.installer.AddHeaders( "./", "*.h" )

env.SetOption('implicit_cache',1)

